---
abstract: 'Build your distributions like Bioperl does'
author:
  - 'BioPerl Team <bioperl-l@lists.open-bio.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-BioPerl
requires:
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 1.00
  MooseX::AttributeShortcuts: 0
  MooseX::Types::Email: 0
  MooseX::Types::Moose: 0
  MooseX::Types::URI: 0
  Pod::Weaver::Config::Assembler: 0
  namespace::autoclean: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://redmine.open-bio.org/projects/bioperl/
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-BioPerl
  repository: git://github.com/bioperl/dist-zilla-pluginbundle-bioperl.git
version: 0.20
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@BioPerl/@Filter/GatherDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@BioPerl/@Filter/PruneCruft'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@BioPerl/@Filter/ManifestSkip'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@BioPerl/@Filter/MetaYAML'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::License
      name: '@BioPerl/@Filter/License'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@BioPerl/@Filter/ExtraTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@BioPerl/@Filter/ExecDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@BioPerl/@Filter/ShareDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@BioPerl/@Filter/MakeMaker'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@BioPerl/@Filter/Manifest'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@BioPerl/@Filter/TestRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@BioPerl/@Filter/ConfirmRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@BioPerl/@Filter/UploadToCPAN'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@BioPerl/MetaConfig'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@BioPerl/MetaJSON'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@BioPerl/PkgVersion'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@BioPerl/PodSyntaxTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@BioPerl/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@BioPerl/NextRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@BioPerl/Test::Compile'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@BioPerl/PodCoverageTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@BioPerl/MojibakeTests'
      version: 0.5
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@BioPerl/AutoPrereqs'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@BioPerl/AutoMetaResources'
      version: 1.110050
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@BioPerl/MetaResources'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@BioPerl/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@BioPerl/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@BioPerl/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@BioPerl/Git::Check'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@BioPerl/Git::Commit'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@BioPerl/Git::Tag'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300020
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300020
x_authority: cpan:BIOPERLML
